import 'dotenv/config';
import mongoose from 'mongoose';
import { connectDatabase } from '../src/config/db.js';
import About from '../src/models/About.js'; import Achievement from '../src/models/Achievement.js'; import Contact from '../src/models/Contact.js'; import Education from '../src/models/Education.js'; import Experience from '../src/models/Experience.js'; import Hero from '../src/models/Hero.js'; import Project from '../src/models/Project.js'; import Skill from '../src/models/Skill.js';

const replace = (Model, rows) => Model.deleteMany({}).then(() => Model.insertMany(rows));
await connectDatabase();
await Promise.all([
  Hero.findOneAndUpdate({ singletonKey: 'hero' }, { name: 'Adnan Khan', role: 'B.Tech IT Student & Developer', headline: 'Building useful web ideas.', availabilityLabel: 'Say hello', intro: 'Adnan is a B.Tech Information Technology student at UIT-RGPV, Bhopal. He builds web applications that are clear, useful and easy to use.', profileImage: '/images/hero-editorial.png', ctas: [{ label: 'Explore projects', url: '#work' }] }, { upsert: true, new: true }),
  About.findOneAndUpdate({ singletonKey: 'about' }, { bio: 'I am improving my Java, DSA and MERN skills while building practical web projects. I enjoy taking an idea and turning it into a simple, useful product.', image: '/images/about-editorial.png', location: 'Bhopal, Madhya Pradesh', quickFacts: [{ label: 'Study', value: 'B.Tech IT, expected 2027' }], heading: 'Learning, building and solving real problems.', ctaLabel: 'Get in touch', ctaUrl: '#contact', visualEyebrow: 'Currently learning / 2026', visualTitle: 'Java DSA + MERN Stack Development.', visualCaption: 'Coding Thinker, Bhopal', visualImage: '/images/landscape-editorial.png' }, { upsert: true, new: true }),
  Contact.findOneAndUpdate({ singletonKey: 'contact' }, { email: 'adnanuitit@gmail.com', phone: '+91-7225922802', linkedIn: 'https://www.linkedin.com/in/adnan-khan-743488204/', github: 'https://github.com/4dnan-kh4n', heading: 'Let’s build something', highlightedWord: 'useful.', intro: 'Have a project, an opportunity or a question? Feel free to get in touch.', footerCopyright: 'Adnan Khan' }, { upsert: true, new: true }),
  replace(Skill, [['Development', 'Java, JavaScript, Python, React, Node.js and Express'], ['Databases', 'MongoDB, MySQL and PostgreSQL'], ['Tools', 'Git, GitHub, Postman, VS Code and Render'], ['Core skills', 'DSA, OOP, REST APIs and CRUD applications'], ['Soft skills', 'Quick learning, creative thinking, teamwork and clear communication']].map(([category, name]) => ({ category, name }))),
  replace(Experience, [['2026-01-01', '2026-03-01', 'Web Optimization & SEO Intern', 'Ansoz Creations'], ['2023-09-01', null, 'Java Developer Intern', 'VaultofCodes'], ['2023-05-01', '2023-06-01', 'Web Developer Intern', 'Immensphere'], ['2022-10-01', null, 'Application Tester Intern', 'Wabi Tech']].map(([startDate, endDate, role, company]) => ({ startDate, endDate, role, company, description: role }))),
  replace(Education, [{ degree: 'B.Tech in Information Technology', institution: 'University Institute of Technology, RGPV', startYear: 2024, endYear: 2027, description: 'Bhopal' }, { degree: 'Diploma in Computer Science & Engineering', institution: 'Government Polytechnic College', startYear: 2021, endYear: 2024, description: 'Harda' }]),
  replace(Project, [{ title: 'DBT Mitra', category: 'Full-stack app', description: 'A Smart India Hackathon project with AI help for users. It uses REST APIs and is deployed on Render.', techStack: ['React', 'Node.js', 'MongoDB', 'Hugging Face'], images: ['/images/project-dbt-mitra.png'], featured: true }, { title: 'Chat India', category: 'React app', description: 'A responsive chat application built with reusable React components and deployed on GitHub Pages.', techStack: ['React', 'JavaScript', 'Responsive UI'], images: ['/images/project-chat-india.png'] }, { title: 'E-Learning Platform', category: 'Web platform', description: 'An online learning platform with sign-in, quizzes, file uploads and Google Meet integration.', techStack: ['PHP', 'MySQL', 'JavaScript'], images: ['/images/project-elearning.png'] }, { title: 'MediTrust', category: 'Healthcare app', description: 'A healthcare-focused web project. Its full details can be added when the project is ready to publish.', techStack: ['Healthcare', 'Web app', 'In development'], images: ['/images/project-meditrust.png'] }]),
  replace(Achievement, [['General Secretary, Student Council', 'Government Polytechnic College, Harda', 'Government Polytechnic College, Harda.'], ['GirlScript Summer of Code Contributor', 'GirlScript Foundation', 'Selected for the Extended 2024 open-source program to work with developers and mentors on real projects.'], ['Standards Club Member', 'Bureau of Indian Standards', 'Completed all Bureau of Indian Standards activities and received a certificate.'], ['3rd place, BIS essay competition', 'Bureau of Indian Standards', 'Won the competition for an essay on ISO Standards and helped raise standards awareness through a nukkad natak.'], ['Voting awareness nukkad natak', 'Jila Panchayat Harda', 'Performed at Government Hospital, Harda. The team received a certificate from the CEO of Jila Panchayat Harda.'], ['Oracle Java Explorer badge', 'Oracle', 'Earned for learning and exploring Java.'], ['IBM Artificial Intelligence Fundamentals', 'IBM SkillsBuild', 'Issued August 29, 2026. Covers AI basics, machine learning, deep learning, AI ethics and IBM Watson Studio.']].map(([title, organization, description]) => ({ title, organization, description })))
]);
console.log('Portfolio data seeded.'); await mongoose.disconnect();
